### PR TITLE
Added Concourse support

### PR DESCRIPTION
**Pull request by carlosgarciaalvarado**
Included build.sh file and maven jars.

### CODE REVIEW

**Comment by carlosgarciaalvarado** [comment]
This is not great if we wanted to contribute this back to the community but I guess we can always build a patch. However, this should simplify building this in Concourse.

**Comment by elalonde** [comment]
Looks good. Just want to confirm there is nothing in this PR that is a secret, since this repository is open to the public (it is a clone of a public repo)

**Comment by carlosgarciaalvarado** [comment]
Agreed. I did not identify anything sensitive.

**Comment by carlosgarciaalvarado** [comment]
Merging.

**Pull request merged**
